# Generated by Django 3.0.5 on 2020-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('IMG', models.ImageField(upload_to='pics')),
                ('UPDATED_DATE', models.DateField()),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('AREA_CODE', models.IntegerField()),
                ('DESC', models.TextField()),
                ('PRICE', models.IntegerField()),
                ('STATUS', models.BooleanField(default=False)),
                ('AGR_AUTO_UUPDATE', models.BooleanField(default=False)),
            ],
        ),
    ]
