# Generated by Django 3.0.5 on 2020-04-12 15:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGREEMENT_TYPE', models.CharField(max_length=10)),
                ('AGREEMENT_VERSION', models.IntegerField()),
                ('START_DATE', models.DateField()),
                ('END_DATE', models.DateField()),
                ('STATUS', models.BooleanField(default=False)),
                ('AUTO_UPDATE', models.BooleanField(default=False)),
                ('TOTAL_AMOUNT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('COMPANY_NAME', models.CharField(max_length=100)),
                ('PAYER_NAME', models.CharField(max_length=100)),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('CONTACT_NUMBER', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('AREA_CODE', models.IntegerField()),
                ('STATUS', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=100)),
                ('PASSWORD', models.IntegerField()),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('CONTACT_NUMBER', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
