# Generated by Django 3.0.5 on 2020-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20200413_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement_details',
            name='AGREEMENT_TYPE',
            field=models.CharField(max_length=20),
        ),
    ]
